version: '4'

services:
  mysql:
    image: mysql:5.7
    volumes:
      - mysql-data:/var/lib/mysql
    environment: 
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: mysql
    networks:
      - web

  wordpress:
    image: wordpress:latest
    ports:
      - 8000:80
    restart: always
    volumes: ['./:/var/www/html']
    environment:
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=wordpress
      - WORDPRESS_DB_NAME=wordpress
    networks:
      - web

volumes:
  mysql-data:
networks:
  web: